### ISSUE TITLE
Only run helm upgrade of changes are needed

### ISSUE THREAD

**Issue by bakito** [snorwin/argocd-operator-extension#4]
It seems that the helm chart is applied on every reconcile even if the crd does not have any changes. 

![image](https://user-images.githubusercontent.com/2733215/108522592-45cf2e80-72cd-11eb-84e1-61c88c5f1b5e.png)

Somehow the operatro should keep track of crd revisions.

**Comment by snorwin** [comment]
Good point, however the extension also needs to keep track of the namespace labels therefore a in-memory state could be used which includes the CR revision as well as all labeled namespaces.

**Comment by bakito** [comment]
Perhaps the infomation could be hashed and stored in an annotation.

**Comment by snorwin** [comment]
Sounds like a plan, but we have to be careful, because updating the ArgoCD CR also triggers a reconcile in the original operator, that it doesn't trigger an infinite loop of reconciles between the operator and the extension.

**Comment by snorwin** [comment]
After a restart/upgrade of the extension pod the helm chart in the config map might have changed and a helm upgrade should be executed. Therefore the revision/state of that config map should also be part of the hash or a state hold in memory is still more appropriate for this additional requirement.
